use std::fs;
use serde::{Serialize, Deserialize};
use dialoguer::{Input, Select};
use uuid::Uuid;
use serde_json::json;
use std::env;
use clap::Parser;
use std::process::Command;
use tokio;
use chrono;
use tracing::{info, warn, error, debug, trace};
use anyhow::Result as AnyhowResult;
use logging::{LoggingConfig, init_logging, init_default_logging, log_error, log_info, log_warning};