name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-ubuntu-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-unknown-linux-gnu
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: aicommit-linux-x86_64
          path: ./target/x86_64-unknown-linux-gnu/release/aicommit

  build-ubuntu-arm:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm base-devel git rust curl aarch64-linux-gnu-gcc
          pacman -S --noconfirm aarch64-linux-gnu-glibc openssl pkg-config
          pacman -S --noconfirm aarch64-linux-gnu-binutils
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          export PKG_CONFIG_ALLOW_CROSS=1
          export OPENSSL_DIR=/usr
          export OPENSSL_LIB_DIR=/usr/lib
          export OPENSSL_INCLUDE_DIR=/usr/include
      - name: Build
        run: |
          export PKG_CONFIG_ALLOW_CROSS=1
          export OPENSSL_DIR=/usr
          export OPENSSL_LIB_DIR=/usr/lib
          export OPENSSL_INCLUDE_DIR=/usr/include
          $HOME/.cargo/bin/rustup target add aarch64-unknown-linux-gnu
          $HOME/.cargo/bin/cargo build --release --target aarch64-unknown-linux-gnu
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: aicommit-linux-arm64
          path: ./target/aarch64-unknown-linux-gnu/release/aicommit

  build-macos-x86:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-apple-darwin
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-apple-darwin
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: aicommit-macos-x86_64
          path: ./target/x86_64-apple-darwin/release/aicommit

  build-macos-arm:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-apple-darwin
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target aarch64-apple-darwin
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: aicommit-macos-arm64
          path: ./target/aarch64-apple-darwin/release/aicommit

  build-windows-x86:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target x86_64-pc-windows-msvc
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: aicommit-windows-x86_64
          path: ./target/x86_64-pc-windows-msvc/release/aicommit.exe

  build-windows-arm:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-pc-windows-msvc
          override: true
      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target aarch64-pc-windows-msvc
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: aicommit-windows-arm64
          path: ./target/aarch64-pc-windows-msvc/release/aicommit.exe

  create-release:
    needs: [build-ubuntu-x86, build-ubuntu-arm, build-macos-x86, build-macos-arm, build-windows-x86, build-windows-arm]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Download all artifacts
        uses: actions/download-artifact@v2
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            artifacts/aicommit-linux-x86_64/aicommit
            artifacts/aicommit-linux-arm64/aicommit
            artifacts/aicommit-macos-x86_64/aicommit
            artifacts/aicommit-macos-arm64/aicommit
            artifacts/aicommit-windows-x86_64/aicommit.exe
            artifacts/aicommit-windows-arm64/aicommit.exe